export interface LessonTime {
  start: {
    weekDay: number;
    hour: number;
  };
  end: {
    weekDay: number;
    hour: number;
  };
}

export interface TALesson {
  uid: number;
  LessonId: number;
  group: string;
  title: string;
  ta: string;
  times: LessonTime[];
}

export interface Lesson {
  uid: number;
  group: string;
  title: string;
  professor: string;
  times: LessonTime[];
}

export enum Universities {
  AMIRKABIR = "Amirkabir University of Technology",
  SHARIF = "Sharif University of Technology",
  TEHRAN = "University of Tehran",
  OTHER1 = "OTHER",
}

export enum Faculties {
  INDUSTRIAL_AND_SYSTEMS_ENGINEERING = 0,
  MECHANICAL_AEROSPACE_MARINE_ENGINEERING = 1,
  MATERIALS_AND_ADVANCED_PROCESSES = 2,
  ELECTRICAL_COMPUTER_BIOMEDICAL_ENGINEERING = 3,
  PETROLEUM_CIVIL_MINING_ENGINEERING = 4,
  SCIENCE = 5,
  MATH_LASER_OPTICS_RESEARCH = 6,
  FOREIGN_LANGUAGES = 7,
  PHYSICAL_EDUCATION = 8,
  INTERNATIONAL_LANGUAGE_CENTER = 9,
  ROBOTICS = 10,
  MECHATRONICS = 11,
  MATERIALS_AND_CORROSION = 12,
  TEXTILE_ENGINEERING = 13,
  POLYMER_ENGINEERING = 14,
  CHEMICAL_ENGINEERING = 15,
  COMPUTER_ENGINEERING = 16,
  INDUSTRIAL_ENGINEERING_AND_MANAGEMENT_SYSTEMS = 17,
  CIVIL_AND_ENVIRONMENTAL_ENGINEERING = 18,
  ELECTRICAL_ENGINEERING = 19,
  PHYSICS_AND_ENERGY_ENGINEERING = 20,
  MINING_AND_METALLURGY_ENGINEERING = 21,
  PETROLEUM_ENGINEERING = 22,

  // Sharif
  AEROSPACE_ENGINEERING = 23,
  CHEMICAL_AND_PETROLEUM_ENGINEERING = 24,
  CHEMISTRY = 25,
  CIVIL_ENGINEERING = 26,
  ENERGY_ENGINEERING = 27,
  INDUSTRIAL_ENGINEERING = 28,
  MATERIALS_SCIENCE_AND_ENGINEERING = 29,
  MECHANICAL_ENGINEERING = 30,
  MATHEMATICAL_SCIENCES = 31,
  PHYSICS = 32,
  MANAGEMENT_AND_ECONOMICS = 33,
  LANGUAGES_AND_LINGUISTICS = 34,
  PHILOSOPHY_OF_SCIENCE = 35,

  // Tehran
  BUSINESS_AND_FINANCE = 36,
  WORLD_STUDIES = 37,
  VETERINARY_MEDICINE = 38,
  THEOLOGY_AND_ISLAMIC_STUDIES = 39,
  SOCIAL_SCIENCES = 40,
  PSYCHOLOGY_AND_EDUCATION_SCIENCES = 41,
  PHYSICAL_EDUCATION_AND_SPORT_SCIENCES = 42,
  MANAGEMENT = 43,
  LITERATURE_AND_HUMANITIES = 44,
  LAW_AND_POLITICAL_SCIENCE = 45,
  ISLAMIC_THOUGHT_AND_STUDIES = 46,
  GEOGRAPHY = 47,
  FOREIGN_LANGUAGES_AND_LITERATURE = 48,
  ENTREPRENEURSHIP = 49,
  ECONOMICS = 50,
  SCIENCE_AND_NEW_TECHNOLOGIES = 51,
  ART = 52,
  AGRICULTURE_AND_NATURAL_RESOURCES = 53,
}
