name: CI/CD Deploy

on:
  push:
    branches:
      - main   # runs only on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # Build and push image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/gamecraft:latest
          docker build -t $IMAGE_NAME -f apps/game_craft/Dockerfile .
          docker push $IMAGE_NAME

      # Deploy to server
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/gamecraft:latest
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull $IMAGE_NAME
            docker stop gamecraft || true
            docker rm gamecraft || true
            docker run -d --name gamecraft -p 3002:3000 --restart always $IMAGE_NAME
